### ISSUE TITLE
Github page is down 

### ISSUE THREAD

**Issue by programmerraja** [thoughtspile/thoughtspile.github.io#3]
Hey hai @thoughtspile  I wanted to bring to your attention that your blog appears to be currently unavailable.  i am not sure you aware of it i just would like to inform you incase you not know yet.

https://blog.thoughtspile.tech/ 

![Screenshot from 2024-01-21 14-51-49](https://github.com/thoughtspile/thoughtspile.github.io/assets/44333589/e29c9703-1257-42a6-9700-11b97403f87a)

**Comment by thoughtspile** [comment]
Hey @programmerraja, thanks for the heads up! The blog is accessible at https://thoughtspile.github.io and the redirects from https://blog.thoughtspile.tech/ should kick in tomorrow, once the DNS caches update.

For some reason google search ranker seems to hate thoughtspile.tech domain, trying to fix it by moving stuff around.
